import React from 'react';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { afterEach, expect, it, vi } from 'vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { PluginHostProps } from '@getpaseo/plugin/client';
const rpc = vi.hoisted(() => ({ list: vi.fn(), terminate: vi.fn() }));
vi.mock('react-native', () => ({ View: 'View', Text: 'Text', Pressable: 'Pressable' }));
vi.mock('@getpaseo/plugin/client/react-native', () => ({ ScrollView: 'ScrollView' }));
vi.mock('@getpaseo/plugin/client', () => ({ useRpc: (contract: { name: string }) => contract.name.endsWith('.list') ? rpc.list : rpc.terminate }));
import { ProcessPanel } from '../client/processes';
const theme = { colors: { foreground: '#eee', foregroundMuted: '#888', surface1: '#222', surface2: '#333', border: '#444' } } as PluginHostProps['theme'];
const entry = { pid: 123, start: '90071992547409999', group: 'codex', name: 'codex', memoryBytes: 100, cpuPercent: 0.4 };
let renderer: ReactTestRenderer | undefined;
afterEach(async () => { if (renderer) await act(async () => renderer!.unmount()); renderer = undefined; vi.clearAllMocks(); });
it('선택만으로 종료하지 않으며 갱신 중 PID가 재사용돼도 확인한 시작 시각을 전송', async () => {
  (globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
  const client = new QueryClient({ defaultOptions: { queries: { gcTime: 0 } } });
  rpc.list.mockResolvedValue({ status: 'ok', sampledAt: Date.now(), entries: [entry] });
  rpc.terminate.mockResolvedValueOnce({ sent: false, error: 'PID 변경' });
  await act(async () => { renderer = create(<QueryClientProvider client={client}><ProcessPanel group="codex" theme={theme} onBack={() => {}} /></QueryClientProvider>); });
  await act(async () => renderer!.root.findByProps({ accessibilityLabel: 'PID 123 종료 선택' }).props.onPress());
  expect(rpc.terminate).not.toHaveBeenCalled();
  client.setQueryData(['mac-monitor', 'processes', 'codex'], { status: 'ok', entries: [{ ...entry, start: 'new-start' }] });
  await act(async () => renderer!.root.findByProps({ accessibilityLabel: 'PID 123 종료 확인' }).props.onPress());
  expect(rpc.terminate).toHaveBeenCalledWith({ pid: 123, start: entry.start, group: 'codex' });
  expect(JSON.stringify(renderer!.toJSON())).toContain('PID 변경');
  expect(JSON.stringify(renderer!.toJSON())).not.toContain('종료 요청을 보냈습니다');
  client.clear();
});
