import React from 'react';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { afterEach, expect, it, vi } from 'vitest';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import type { PluginHostProps } from '@getpaseo/plugin/client';
const rpc = vi.hoisted(() => ({ list: vi.fn(), terminate: vi.fn(), group: vi.fn() }));
vi.mock('react-native', () => ({ View: 'View', Text: 'Text', Pressable: 'Pressable' }));
vi.mock('@getpaseo/plugin/client/react-native', () => ({ ScrollView: 'ScrollView' }));
vi.mock('@getpaseo/plugin/client', () => ({ useRpc: (contract: { name: string }) => contract.name.endsWith('.list') ? rpc.list : contract.name === 'mac-monitor.group.terminate' ? rpc.group : rpc.terminate }));
import { GroupTermination, ProcessPanel } from '../client/processes';
const theme = { colors: { foreground: '#eee', foregroundMuted: '#888', surface1: '#222', surface2: '#333', border: '#444' } } as PluginHostProps['theme'];
const entry = { pid: 123, start: '90071992547409999', group: 'codex', name: 'codex', memoryBytes: 100, cpuPercent: 0.4 };
let renderer: ReactTestRenderer | undefined;
afterEach(async () => { if (renderer) await act(async () => renderer!.unmount()); renderer = undefined; vi.clearAllMocks(); });
it('선택만으로 종료하지 않으며 갱신 중 PID가 재사용돼도 확인한 시작 시각을 전송', async () => {
  (globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
  const client = new QueryClient({ defaultOptions: { queries: { gcTime: 0 } } });
  rpc.list.mockResolvedValue({ status: 'ok', sampledAt: Date.now(), entries: [entry] });
  rpc.terminate.mockResolvedValueOnce({ sent: false, error: 'PID 변경' });
  await act(async () => { renderer = create(<QueryClientProvider client={client}><ProcessPanel group="codex" theme={theme} onBack={() => {}} /></QueryClientProvider>); });
  await act(async () => renderer!.root.findByProps({ accessibilityLabel: 'PID 123 종료 선택' }).props.onPress());
  expect(rpc.terminate).not.toHaveBeenCalled();
  client.setQueryData(['mac-monitor', 'processes', 'codex'], { status: 'ok', entries: [{ ...entry, start: 'new-start' }] });
  await act(async () => renderer!.root.findByProps({ accessibilityLabel: 'PID 123 종료 확인' }).props.onPress());
  expect(rpc.terminate).toHaveBeenCalledWith({ pid: 123, start: entry.start, group: 'codex' });
  expect(JSON.stringify(renderer!.toJSON())).toContain('PID 변경');
  expect(JSON.stringify(renderer!.toJSON())).not.toContain('종료 요청을 보냈습니다');
  client.clear();
});
it('전체 종료는 확인한 목록을 고정하고 새 프로세스를 추가하지 않으며 부분 실패를 표시', async () => {
  const client = new QueryClient({ defaultOptions: { queries: { gcTime: 0 } } });
  const other = { ...entry, pid: 124 };
  rpc.list.mockResolvedValue({ status: 'ok', entries: [entry, other] });
  rpc.group.mockResolvedValue({ results: [{ pid: 123, sent: true }, { pid: 124, sent: false, error: '보호된 프로세스' }] });
  await act(async () => { renderer = create(<QueryClientProvider client={client}><GroupTermination group="codex" theme={theme} onBack={() => {}} /></QueryClientProvider>); });
  expect(rpc.group).not.toHaveBeenCalled();
  expect(JSON.stringify(renderer!.toJSON())).toContain('2개');
  client.setQueryData(['mac-monitor', 'terminate-group', 'codex'], { status: 'ok', entries: [{ ...entry, pid: 999 }] });
  await act(async () => renderer!.root.findByProps({ accessibilityLabel: 'codex 전체 종료 확인' }).props.onPress());
  expect(rpc.group).toHaveBeenCalledExactlyOnceWith({ group: 'codex', targets: [{ pid: 123, start: entry.start }, { pid: 124, start: entry.start }] });
  expect(renderer!.root.findAll(node => String(node.type) === 'Text').map(node => node.children.join(''))).toContain('종료 요청 1개 · 보내지 못함 1개');
  expect(JSON.stringify(renderer!.toJSON())).toContain('보호된 프로세스');
  client.clear();
});
it('전체 종료 확인을 취소하면 종료 요청을 보내지 않음', async () => {
  const client = new QueryClient(); const onBack = vi.fn();
  rpc.list.mockResolvedValue({ status: 'ok', entries: [entry] });
  await act(async () => { renderer = create(<QueryClientProvider client={client}><GroupTermination group="codex" theme={theme} onBack={onBack} /></QueryClientProvider>); });
  await act(async () => renderer!.root.findByProps({ accessibilityLabel: '상위 앱으로 돌아가기' }).props.onPress());
  expect(onBack).toHaveBeenCalledOnce(); expect(rpc.group).not.toHaveBeenCalled();client.clear();
});
